### ISSUE TITLE
Add a setup.py, add to PyPI

### ISSUE THREAD

**Issue by dgouldin** [pganalyze/pganalyze-collector#6]
By making this tool a real python package, you could make it pip installable rather than requiring modification of apt sources or downloading and unzipping the code directly.

**Comment by lfittl** [comment]
Good idea!

We're currently looking into re-releasing this as an open-source Go daemon (likely in the next few weeks), since that will make us less dependent on the local environments, and give us some better options in terms of realtime monitoring (not just every 10 minutes in the crontab).

Hence, I'll close this issue for now, but I'd be happy to take a patch if you'd find this tool useful outside of what we use it for here. :)
