### ISSUE TITLE
pganalyze-collector fails on pgsql-9.6beta2

### ISSUE THREAD

**Issue by jmscott** [pganalyze/pganalyze-collector#8]
testing pganalyze against 9.6beta2. i get the following error where running ./pganalyze-collector.py: 

ERROR - 2016-07-13 12:19:52,529 Got an error during query execution 
ERROR - 2016-07-13 12:19:52,529 ('ERROR', '42703', 'column "waiting" does not exist')

**Comment by lfittl** [comment]
I realized I never responded to you here, only in private communication.

For future reference, PostgreSQL 9.6 is only supported by the newer Go-based pganalyze collector, which can be found here: https://github.com/pganalyze/collector

It is part of the release testing there, and the issue at hand has been resolved since release 0.9.3. Thanks again for reporting!
